[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-utilities"
version = "0.0.0a1"
readme = "README.md"
dependencies = [
    "ipywidgets>=8.0.2"
]